name = "web3-design-principles"
type = "webpack"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = "./dist/public"
entry-point = "workers-site"

[build]
command = "npm run build"
upload.format = "service-worker"

[env.production]
name = "web3-design-principles-prod"
route = ""
