name = "web3-design-principles"
compatibility_date = "2024-01-01"

# This configuration is for Cloudflare Pages
# Build output directory matches vite.config.ts build.outDir
pages_build_output_dir = "dist/public" 