name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy:
    # Only run on main branch pushes or merged PRs
    if: github.ref == 'refs/heads/main' || (github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main')
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages
    
    # Add environment protection (optional but recommended)
    environment:
      name: production
      url: https://web3-design-principles.pages.dev
    
    # Security: Limit permissions
    permissions:
      contents: read
      deployments: write
      pull-requests: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build:client

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: web3-design-principles
          directory: dist/public
          # Optional: git info
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '3' 